spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route-picture-service
          uri: lb://picture-service
          predicates:
            - Path=/test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

