eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
spring:
  application:
    name: main-entance
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boomshair?autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
  session:
    store-type: redis
    timeout: 3000
  cloud:
    gateway:
      routes:
        - id: route-picture-service
          uri: lb://picture-service
          predicates:
            - Path=/picture/**
            - After=2021-08-25T10:22:33.789+08:00
        - id: ask-baidu
          uri: http://www.baidu.com
          predicates:
            - After=2021-08-25T10:22:33.789+08:00